import { StyleSheet, Platform, Dimensions } from "react-native";

export const mainScreenStyles = StyleSheet.create({
  container: {
    display: "flex",
    flex: 1,
  },
  topView: {
    flex: 0.6,
    backgroundColor: "#7165E3",
    paddingTop: Platform.OS === "android" ? 60 : 70,
  },
  subTopView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  leftTopView: {
    display: "flex",
    flexDirection: "column",
    gap: 25,
  },
  topViewTopAvailableBal: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: Platform.OS === "android" ? 35 : 37,
  },
  topViewBottomAvailableBal: {
    color: "#FFFFFF",
    fontWeight: "400",
    fontSize: Platform.OS === "android" ? 15 : 17,
  },
  topViewLeftImage: {
    height: 20,
    width: 85,
  },
  bottomView: {
    flex: 1,
    backgroundColor: "whitesmoke",
  },
  chartCardView: {
    width: "93%",
    height: 212,
    backgroundColor: "white",
    borderWidth: 0.5,
    borderColor: "gainsboro",
    alignSelf: "center",
    borderRadius: 10,
    marginTop: -115,
    position: "relative",
    display: "flex",
    justifyContent: "center",
  },
  chartCardInnerTop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 20,
    paddingRight: 50,
    paddingBottom: 20,
  },
  divider: {
    borderBottomWidth: 0.5,
    borderColor: "gainsboro",
    display: "flex",
    position: "relative",
  },
  chartCardTopTextContent: {
    paddingTop: 20,
    color: "#1C1939",
    fontSize: 13,
    fontWeight: "400",
    textAlign: "left",
    paddingLeft: 25,
    lineHeight: 20,
  },
  chartCardBottomTextContent: {
    paddingTop: 10,
    color: "#7165E3",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "left",
    paddingLeft: 28,
  },
  activityView: {
    display: "flex",
    flexDirection: "column",
    marginTop: 30,
    gap: 30,
  },
  activityText: {
    color: "#1C1939",
    fontWeight: "700",
    fontSize: 18,
    textAlign: "left",
    paddingLeft: 12,
    paddingTop: 30,
  },
  activityBtnView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  activityBtnImgView: {
    backgroundColor: "#7165E3",
    width: 38,
    height: 38,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  activityBtn: {
    backgroundColor: "#FFFFFF",
    width: 107,
    height: 114,
    borderWidth: 0.5,
    borderColor: "gainsboro",
    borderRadius: 20,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  activityBtnTxt: {
    fontWeight: "400",
    fontSize: 13,
    color: "#1C1939",
    paddingTop: 15,
  },
  verificationText: {
    color: "#1C1939",
    fontWeight: "700",
    fontSize: 18,
    textAlign: "left",
    paddingLeft: 12,
  },
  verificationView: {
    display: "flex",
    flexDirection: "column",
    gap: 30,
  },
  subVerificationView: {
    width: "93%",
    height: 490,
    backgroundColor: "white",
    borderWidth: 0.5,
    borderColor: "gainsboro",
    alignSelf: "center",
    borderRadius: 10,
    position: "relative",
    display: "flex",
  },
  percentView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 10,
    paddingRight: 10,
    width: "95%",
    alignSelf: "center",
    paddingTop: 30,
  },
  sevntyFivePercent: {
    color: "#1C1939",
    fontWeight: "700",
    fontSize: 25,
  },
  completedText: {
    color: "#1C1939",
    fontSize: 12,
    fontWeight: "400",
    paddingTop: 10,
  },
  progressBarView: {
    height: 10,
    backgroundColor: "#ccc",
    borderRadius: 10,
    overflow: "hidden",
    margin: 10,
  },
  bar: {
    height: 10,
    backgroundColor: "#7165E3",
    width: "75%",
  },
  personalInformationView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  personalInformationText: {
    color: "#1C1939",
    fontWeight: "700",
    fontSize: 14,
  },
  personalInformationSubText: {
    color: "#1C1939",
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 20,
  },
  personalInformation: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  personalInformationBottomText: {
    paddingTop: 10,
    color: "#7165E3",
    fontSize: 13,
    fontWeight: "700",
  },
  verificationView2: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  subNewsAndPromo: {
    width: "95%",
    height: 322,
    backgroundColor: "white",
    borderWidth: 0.5,
    borderColor: "gainsboro",
    alignSelf: "center",
    borderRadius: 10,
    position: "relative",
    display: "flex",
    overflow: "hidden",
  },
  newsAndPromo: {
    display: "flex",
    flexDirection: "column",
    gap: 30,
  },
  newsAndPromoText: {
    color: "#1C1939",
    fontWeight: "700",
    fontSize: 18,
    textAlign: "left",
    paddingLeft: 12,
    paddingTop: 20,
  },
});
